// <auto-generated />
using System;
using Genaralinsuranceapp.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Genaralinsuranceapp.Migrations
{
    [DbContext(typeof(generalinsuranceContext))]
    [Migration("20220323105036_CreateGeneralInsurance")]
    partial class CreateGeneralInsurance
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Genaralinsuranceapp.Repository.Claimdata", b =>
                {
                    b.Property<int>("PolicyNumber")
                        .HasColumnName("policy_number")
                        .HasColumnType("int");

                    b.Property<int?>("ClaimId")
                        .HasColumnName("claim_id")
                        .HasColumnType("int");

                    b.HasKey("PolicyNumber")
                        .HasName("PK__Claimdat__96916873961704A3");

                    b.HasIndex("ClaimId");

                    b.ToTable("Claimdata");
                });

            modelBuilder.Entity("Genaralinsuranceapp.Repository.Claimhistory", b =>
                {
                    b.Property<int>("ClaimNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("claim_no")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal?>("Amount")
                        .HasColumnName("amount")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<int?>("ClaimId")
                        .HasColumnName("claim_id")
                        .HasColumnType("int");

                    b.Property<bool?>("IsApproved")
                        .HasColumnName("is_Approved")
                        .HasColumnType("bit");

                    b.Property<int?>("PolicyNumber")
                        .HasColumnName("policy_number")
                        .HasColumnType("int");

                    b.HasKey("ClaimNo")
                        .HasName("PK__claimhis__F9CC1145BDF7E59B");

                    b.HasIndex("ClaimId");

                    b.HasIndex("PolicyNumber");

                    b.ToTable("claimhistory");
                });

            modelBuilder.Entity("Genaralinsuranceapp.Repository.Claimreasons", b =>
                {
                    b.Property<int>("ClaimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("claim_id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Claimreason")
                        .HasColumnName("claimreason")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("ClaimId")
                        .HasName("PK__claimrea__F9CC0896B5DA3726");

                    b.ToTable("claimreasons");
                });

            modelBuilder.Entity("Genaralinsuranceapp.Repository.CustomerRegistration", b =>
                {
                    b.Property<long>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("customer_id")
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("varchar(max)")
                        .IsUnicode(false);

                    b.Property<string>("ContactNo")
                        .HasColumnName("contact_no")
                        .HasColumnType("varchar(10)")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<DateTime?>("Dob")
                        .HasColumnName("DOB")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .HasColumnName("email")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("FirstName")
                        .HasColumnName("First_Name")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Password")
                        .HasColumnName("password")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<int?>("PolicyNumber")
                        .HasColumnName("policy_number")
                        .HasColumnType("int");

                    b.HasKey("CustomerId")
                        .HasName("PK__Customer__CD65CB8517EE82D5");

                    b.ToTable("Customer_Registration");
                });

            modelBuilder.Entity("Genaralinsuranceapp.Repository.Insuranceduration", b =>
                {
                    b.Property<int>("DurationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("duration_id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DurationValue")
                        .HasColumnName("duration_value")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("DurationId")
                        .HasName("PK__insuranc__7EB98060C42ACC99");

                    b.ToTable("insuranceduration");
                });

            modelBuilder.Entity("Genaralinsuranceapp.Repository.Insuranceplantype", b =>
                {
                    b.Property<int>("PlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("plan_id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Planname")
                        .HasColumnName("planname")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("PlanId")
                        .HasName("PK__insuranc__BE9F8F1D13E9C4E1");

                    b.ToTable("insuranceplantype");
                });

            modelBuilder.Entity("Genaralinsuranceapp.Repository.Login", b =>
                {
                    b.Property<string>("Email")
                        .HasColumnName("email")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Password")
                        .HasColumnName("password")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("Email")
                        .HasName("PK__login__AB6E6165D55A04F5");

                    b.ToTable("login");
                });

            modelBuilder.Entity("Genaralinsuranceapp.Repository.Policydetails", b =>
                {
                    b.Property<int>("PolicyNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("policy_number")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("CustomerId")
                        .HasColumnName("customer_id")
                        .HasColumnType("bigint");

                    b.Property<int?>("DurationId")
                        .HasColumnName("duration_id")
                        .HasColumnType("int");

                    b.Property<int?>("PlanId")
                        .HasColumnName("plan_id")
                        .HasColumnType("int");

                    b.Property<int?>("VehicletypeId")
                        .HasColumnName("vehicletype_id")
                        .HasColumnType("int");

                    b.HasKey("PolicyNumber")
                        .HasName("PK__policyde__96916873F4BE3DCA");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DurationId");

                    b.HasIndex("PlanId");

                    b.HasIndex("VehicletypeId");

                    b.ToTable("policydetails");
                });

            modelBuilder.Entity("Genaralinsuranceapp.Repository.Vehiclesdetails", b =>
                {
                    b.Property<string>("RegistrationNumber")
                        .HasColumnName("registration_number")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("ChasisNumber")
                        .HasColumnName("chasis_number")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<long?>("CustomerId")
                        .HasColumnName("customer_id")
                        .HasColumnType("bigint");

                    b.Property<string>("DrivingLicenseNumber")
                        .HasColumnName("driving_license_number")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("EngineNumber")
                        .HasColumnName("engine_number")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("Manufacturer")
                        .HasColumnName("manufacturer")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Model")
                        .HasColumnName("model")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<int?>("PolicyNumber")
                        .HasColumnName("policy_number")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PurchaseDate")
                        .HasColumnName("purchase_date")
                        .HasColumnType("date");

                    b.Property<string>("VehicleType")
                        .HasColumnName("Vehicle_Type")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("RegistrationNumber")
                        .HasName("PK__vehicles__125DB2A2B93D18C0");

                    b.HasIndex("CustomerId");

                    b.HasIndex("PolicyNumber");

                    b.ToTable("vehiclesdetails");
                });

            modelBuilder.Entity("Genaralinsuranceapp.Repository.Vehicletypes", b =>
                {
                    b.Property<int>("VehicletypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("vehicletype_id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Vehicletype")
                        .HasColumnName("vehicletype")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("VehicletypeId")
                        .HasName("PK__vehiclet__20A37C0CEA8C5DFF");

                    b.ToTable("vehicletypes");
                });

            modelBuilder.Entity("Genaralinsuranceapp.Repository.Claimdata", b =>
                {
                    b.HasOne("Genaralinsuranceapp.Repository.Claimreasons", "Claim")
                        .WithMany("Claimdata")
                        .HasForeignKey("ClaimId")
                        .HasConstraintName("FK__Claimdata__claim__22751F6C");

                    b.HasOne("Genaralinsuranceapp.Repository.Policydetails", "PolicyNumberNavigation")
                        .WithOne("Claimdata")
                        .HasForeignKey("Genaralinsuranceapp.Repository.Claimdata", "PolicyNumber")
                        .HasConstraintName("FK__Claimdata__polic__2180FB33")
                        .IsRequired();
                });

            modelBuilder.Entity("Genaralinsuranceapp.Repository.Claimhistory", b =>
                {
                    b.HasOne("Genaralinsuranceapp.Repository.Claimreasons", "Claim")
                        .WithMany("Claimhistory")
                        .HasForeignKey("ClaimId")
                        .HasConstraintName("FK__claimhist__claim__60A75C0F");

                    b.HasOne("Genaralinsuranceapp.Repository.Policydetails", "PolicyNumberNavigation")
                        .WithMany("Claimhistory")
                        .HasForeignKey("PolicyNumber")
                        .HasConstraintName("FK__claimhist__polic__5FB337D6");
                });

            modelBuilder.Entity("Genaralinsuranceapp.Repository.Policydetails", b =>
                {
                    b.HasOne("Genaralinsuranceapp.Repository.CustomerRegistration", "Customer")
                        .WithMany("Policydetails")
                        .HasForeignKey("CustomerId")
                        .HasConstraintName("FK__policydet__vehic__59FA5E80");

                    b.HasOne("Genaralinsuranceapp.Repository.Insuranceduration", "Duration")
                        .WithMany("Policydetails")
                        .HasForeignKey("DurationId")
                        .HasConstraintName("FK__policydet__durat__5AEE82B9");

                    b.HasOne("Genaralinsuranceapp.Repository.Insuranceplantype", "Plan")
                        .WithMany("Policydetails")
                        .HasForeignKey("PlanId")
                        .HasConstraintName("FK__policydet__plan___5BE2A6F2");

                    b.HasOne("Genaralinsuranceapp.Repository.Vehicletypes", "Vehicletype")
                        .WithMany("Policydetails")
                        .HasForeignKey("VehicletypeId")
                        .HasConstraintName("FK__policydet__vehic__5CD6CB2B");
                });

            modelBuilder.Entity("Genaralinsuranceapp.Repository.Vehiclesdetails", b =>
                {
                    b.HasOne("Genaralinsuranceapp.Repository.CustomerRegistration", "Customer")
                        .WithMany("Vehiclesdetails")
                        .HasForeignKey("CustomerId")
                        .HasConstraintName("FK__vehiclesd__custo__6383C8BA");

                    b.HasOne("Genaralinsuranceapp.Repository.Policydetails", "PolicyNumberNavigation")
                        .WithMany("Vehiclesdetails")
                        .HasForeignKey("PolicyNumber")
                        .HasConstraintName("FK__vehiclesd__polic__6477ECF3");
                });
#pragma warning restore 612, 618
        }
    }
}
