// <auto-generated />
using EF_CodeFirst.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EF_CodeFirst.Migrations
{
    [DbContext(typeof(EmployeeDbContext))]
    [Migration("20220311112601_CreateEmpDbProjectNameUpdate")]
    partial class CreateEmpDbProjectNameUpdate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EF_CodeFirst.Repository.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("employeeid")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 100)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasColumnName("employeename")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ProjectName")
                        .HasColumnName("projectname")
                        .HasColumnType("varchar")
                        .HasMaxLength(20);

                    b.Property<decimal>("Salary")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("employeesalary")
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.HasKey("EmployeeId")
                        .HasName("pk_employees_employeeid");

                    b.ToTable("employees");
                });
#pragma warning restore 612, 618
        }
    }
}
